# Generated by Django 2.0.1 on 2018-02-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectconfiguration',
            name='file_description',
            field=models.TextField(blank=True, help_text='Description of the type of data being uploaded.'),
        ),
        migrations.AlterField(
            model_name='projectconfiguration',
            name='file_tags',
            field=models.TextField(blank=True, help_text='List of tags that describe file uploads, stored as a JSON-formatted array'),
        ),
        migrations.AlterField(
            model_name='projectconfiguration',
            name='oh_activity_page',
            field=models.TextField(blank=True, help_text='The URL where we can find your project in Open Humans.'),
        ),
        migrations.AlterField(
            model_name='projectconfiguration',
            name='oh_client_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='projectconfiguration',
            name='oh_client_secret',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='projectconfiguration',
            name='project_description',
            field=models.TextField(blank=True, help_text='Project description, displayed on the front page.'),
        ),
        migrations.AlterField(
            model_name='projectconfiguration',
            name='project_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
