# Generated by Django 2.0.1 on 2018-02-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0002_auto_20180222_1847'),
        ('project_admin', '0002_auto_20180222_1833'),
    ]

    operations = [
    ]
