# Generated by Django 2.0.1 on 2018-02-28 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0003_merge_20180223_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of the file (for representational purposes in the project)')),
                ('description', models.TextField(blank=True, help_text='Description of the type of data being uploaded.')),
                ('tags', models.TextField(blank=True, help_text='List of tags that describe file uploads, stored as a JSON-formatted array')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectconfiguration',
            name='file_description',
        ),
        migrations.RemoveField(
            model_name='projectconfiguration',
            name='file_tags',
        ),
    ]
