# Generated by Django 2.0.2 on 2018-03-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_admin', '0003_merge_20180223_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectconfiguration',
            name='file_tags',
            field=models.TextField(
                blank=True,
                help_text='List of tags that describe file uploads,'
                ' stored as a JSON-formatted array'),
        ),
        migrations.AlterField(
            model_name='projectconfiguration',
            name='oh_activity_page',
            field=models.TextField(
                blank=True,
                help_text='The URL where we can find'
                ' your project in Open Humans.'),
        ),
    ]
